import { DrivingMode, fuelType } from "../interfaces/CarInterfaces";

export const selectPhrases = {
  make: "Select a brand",
  model: "Select a model",
};
export const carBrands = [
  { id: 0, name: selectPhrases.make },
  // { id: 1, name: "Acura" },
  // { id: 2, name: "Alfa Romeo" },
  // { id: 3, name: "Aston Martin" },
  // { id: 4, name: "Audi" },
  // { id: 5, name: "Bentley" },
  { id: 6, name: "Bmw" },
  // { id: 7, name: "BYD" },
  // { id: 8, name: "Chery" },
  // { id: 9, name: "Chevrolet" },
  // { id: 10, name: "Citroën" },
  // { id: 11, name: "Dacia" },
  // { id: 12, name: "Ferrari" },
  // { id: 13, name: "Fiat" },
  // { id: 14, name: "Ford" },
  // { id: 15, name: "Geely" },
  // { id: 16, name: "Haval" },
  // { id: 17, name: "Honda" },
  // { id: 18, name: "Hyundai" },
  // { id: 19, name: "Isuzu" },
  // { id: 20, name: "Jaguar" },
  // { id: 21, name: "Kia" },
  // { id: 22, name: "Land Rover" },
  // { id: 23, name: "Lamborghini" },
  // { id: 24, name: "Lexus" },
  // { id: 25, name: "Mahindra" },
  // { id: 26, name: "Maserati" },
  // { id: 27, name: "Mazda" },
  { id: 28, name: "Mercedes" },
  // { id: 29, name: "Mini" },
  // { id: 30, name: "Mitsubishi" },
  // { id: 31, name: "Nissan" },
  // { id: 32, name: "Opel" },
  // { id: 33, name: "Peugeot" },
  // { id: 34, name: "Porsche" },
  // { id: 35, name: "Proton" },
  // { id: 36, name: "Renault" },
  // { id: 37, name: "Rolls-Royce" },
  // { id: 38, name: "SEAT" },
  // { id: 39, name: "Skoda" },
  // { id: 40, name: "Smart" },
  // { id: 41, name: "SsangYong" },
  // { id: 42, name: "Subaru" },
  // { id: 43, name: "Suzuki" },
  // { id: 44, name: "Tata" },
  // { id: 45, name: "Tesla" },
  // { id: 46, name: "Toyota" },
  // { id: 47, name: "Volkswagen" },
  // { id: 48, name: "Volvo" }
];

export const carModels = {
  bmw: [
    { id: 0, name: selectPhrases.model },
    { id: 1, name: "1 Series" },
    { id: 2, name: "2 Series Coupe" },
    { id: 3, name: "2 Series Gran Coupe" },
    { id: 4, name: "3 Series Sedan" },
    { id: 5, name: "3 Series Touring" },
    { id: 6, name: "4 Series Coupe" },
    { id: 7, name: "4 Series Convertible" },
    { id: 8, name: "4 Series Gran Coupe" },
    { id: 9, name: "5 Series Sedan" },
    { id: 10, name: "5 Series Touring" },
    { id: 11, name: "6 Series Gran Turismo" },
    { id: 12, name: "7 Series Sedan" },
    { id: 13, name: "8 Series Coupe" },
    { id: 14, name: "8 Series Convertible" },
    { id: 15, name: "8 Series Gran Coupe" },
    { id: 16, name: "X1" },
    { id: 17, name: "X2" },
    { id: 18, name: "X3" },
    { id: 19, name: "X4" },
    { id: 20, name: "X5" },
    { id: 21, name: "X6" },
    { id: 22, name: "X7" },
    { id: 23, name: "Z4" },
    { id: 24, name: "i3" },
    { id: 25, name: "i4" },
    { id: 26, name: "i8" },
    { id: 27, name: "iX3" },
    { id: 28, name: "iX" },
    { id: 29, name: "i7" },
    { id: 30, name: "M2" },
    { id: 31, name: "M3" },
    { id: 32, name: "M4" },
    { id: 33, name: "M5" },
    { id: 34, name: "M8" },
    { id: 35, name: "X3 M" },
    { id: 36, name: "X4 M" },
    { id: 37, name: "X5 M" },
    { id: 38, name: "X6 M" },
    { id: 39, name: "X7 M50i" },
  ],
  mercedes: [
    { id: 0, name: selectPhrases.model },
    { id: 1, name: "A-Class" },
    { id: 2, name: "B-Class" },
    { id: 3, name: "C-Class Sedan" },
    { id: 4, name: "C-Class Coupe" },
    { id: 5, name: "C-Class Cabriolet" },
    { id: 6, name: "CLA Coupe" },
    { id: 7, name: "CLS Coupe" },
    { id: 8, name: "E-Class Sedan" },
    { id: 9, name: "E-Class Coupe" },
    { id: 10, name: "E-Class Cabriolet" },
    { id: 11, name: "E-Class Wagon" },
    { id: 12, name: "S-Class Sedan" },
    { id: 13, name: "S-Class Coupe" },
    { id: 14, name: "S-Class Cabriolet" },
    { id: 15, name: "G-Class" },
    { id: 16, name: "GLA SUV" },
    { id: 17, name: "GLB SUV" },
    { id: 18, name: "GLC SUV" },
    { id: 19, name: "GLC Coupe" },
    { id: 20, name: "GLE SUV" },
    { id: 21, name: "GLE Coupe" },
    { id: 22, name: "GLS SUV" },
    { id: 23, name: "EQC" },
    { id: 24, name: "EQA" },
    { id: 25, name: "EQB" },
    { id: 26, name: "EQS" },
    { id: 27, name: "EQS SUV" },
    { id: 28, name: "EQE" },
    { id: 29, name: "EQE SUV" },
    { id: 30, name: "AMG GT Coupe" },
    { id: 31, name: "AMG GT Roadster" },
    { id: 32, name: "AMG GT 4-Door Coupe" },
    { id: 33, name: "SL Roadster" },
    { id: 34, name: "SLC Roadster" },
    { id: 35, name: "V-Class" },
    { id: 36, name: "X-Class" },
  ],
};

export const constructionYears = [
  { id: 1, name: "2015" },
  { id: 2, name: "2016" },
  { id: 3, name: "2017" },
  { id: 4, name: "2018" },
  { id: 5, name: "2019" },
  { id: 6, name: "2020" },
  { id: 7, name: "2021" },
  { id: 8, name: "2022" },
  { id: 9, name: "2023" },
  { id: 10, name: "2024" },
  { id: 11, name: "2025" },
];

export const mileageIntervals = [
  { id: 1, name: "0-30,000 km" },
  { id: 2, name: "30,001-60,000 km" },
  { id: 3, name: "60,001-100,000 km" },
  { id: 4, name: "100,001-150,000 km" },
  { id: 5, name: "150,001+ km" },
];

export const fuelTypes = [
  { id: 1, name: fuelType.petrol },
  { id: 2, name: fuelType.electric },
  { id: 3, name: fuelType.hybrid },
];

export const drivingModes = [
  { id: 1, name: DrivingMode.automatic },
  { id: 2, name: DrivingMode.manual },
];
